name: Auto Merge develop to qa

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history is needed for merge

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Merge main into qa
        run: |
          git fetch origin
          git checkout qa
          git merge origin/main --no-edit
          git push origin qa

